name: Release

on:
  release:
    types:
      - released

jobs:
  deploy:
    name: Deploy library
    runs-on:
      - macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Upload Github
        env:
            RELEASE_NAME: ${{ github.event.release.name }}
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: ./gradlew kmvi:publishAllPublicationsToGitHubPackagesRepository
