name: Release

on:
  release:
    types:
      - released

jobs:
    publish-maven:
        name: Publish to MavenCentral
        runs-on: macOS-latest
        steps:
            -   name: Check out code
                uses: actions/checkout@v5
            -   name: Set up JDK 21
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 21
            -   name: Publish to MavenCentral
                run: ./gradlew publishToMavenCentral --no-configuration-cache
                env:
                    RELEASE_NAME: ${{ github.event.release.name }}
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
